// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "d6d26f79-bdaa-4fc4-a2ce-8d84dd0d8e3b";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onDistChange();
void onBuzzChange();
void onNightLedChange();
void onRedLedChange();
void onEtatChange();

float dist;
CloudLight buzz;
CloudLight night_led;
CloudLight red_led;
int etat;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(dist, READWRITE, ON_CHANGE, onDistChange);
  ArduinoCloud.addProperty(buzz, READWRITE, ON_CHANGE, onBuzzChange);
  ArduinoCloud.addProperty(night_led, READWRITE, ON_CHANGE, onNightLedChange);
  ArduinoCloud.addProperty(red_led, READWRITE, ON_CHANGE, onRedLedChange);
  ArduinoCloud.addProperty(etat, READWRITE, ON_CHANGE, onEtatChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
